name: Test workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches: [dev]
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: echo COMMIT_MESSAGES
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: escape when contains skip
        env: 
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        if: contains(join(env.COMMIT_MESSAGES, ', '), '#skip') == false && github.event_name == 'push' 
        run: echo "deployed"